modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/dima-dencep/online-emotes/issues"
license = "AGPL-3.0-only"

[[mods]]
modId = "online_emotes"
version = "${version}"
displayName = "Online Emotes"
updateJSONURL = "https://api.modrinth.com/updates/online-emotes/forge_updates.json"
authors = "dima_dencep"
credits = "NE4T0, nneewwtt"
displayURL = "https://curseforge.com/minecraft/mc-mods/online-emotes"
description = "Allows players to see each other's emotes without emotecraft installed on the server."
logoFile = "icon.png"

[[dependencies.online_emotes]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.online_emotes]]
modId = "cloth_config"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.online_emotes]]
modId = "emotecraft"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"