modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/dima-dencep/online-emotes/issues"
license = "OSL-3.0"

[[mods]]
modId = "online_emotes"
version = "${version}"
displayName = "Online Emotes"
updateJSONURL = "https://api.modrinth.com/updates/online-emotes/forge_updates.json"
authors = "dima_dencep"
credits = "NE4T0, nneewwtt"
displayURL = "https://curseforge.com/minecraft/mc-mods/online-emotes"
description = "Allows players to see each other's emotes without emotecraft installed on the server."
logoFile = "assets/online-emotes/icon.png"

[[mixins]]
config = "online-emotes.mixins.json"

[[dependencies.online_emotes]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.online_emotes]]
modId = "emotecraft"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"