import org.redlance.dima_dencep.gradle.publish2discord.tasks.PublishDiscordTask
import io.github.p03w.machete.tasks.OptimizeJarsTask

plugins {
    id "org.redlance.dima_dencep.gradle.PublishToDiscord" version "1.0.8"
    id "com.gradleup.shadow" version "9.6.1"
    id "xyz.wagyourtail.unimined" version "1.4.2+redlance.3"
    id "net.neoforged.licenser" version "0.7.5"
    id "org.redlance.dima_dencep.gradle.machete"  version "2.0.0"
}

license {
    header = rootProject.file('HEADER')
    skipExistingHeaders = false

    tasks {
        rrls {
            files.from rootProject.fileTree("src", {
                include "**/*.java"
            })
        }
    }
}

base.archivesName = rootProject.archives_base_name
version = "${rootProject.mod_version}+mc.${rootProject.minecraft_version}"
group = rootProject.maven_group

sourceSets {
    fabric
    neoforge
}

repositories {
    mavenLocal()
    maven {
        name = "RedlancePublic"
        url = "https://repo.redlance.org/public"
    }
    maven {
        name = "NeoForged"
        url = "https://maven.neoforged.net/releases"
    }
    maven {
        name = "TerraformersMC maven"
        url = "https://maven.terraformersmc.com/"
    }
}

configurations {
    shadow

    platformInclude
    fabricInclude.extendsFrom platformInclude
    neoforgeInclude.extendsFrom platformInclude
}

unimined.minecraft(sourceSets.main) {
    version minecraft_version

    fabric {
        loader fabric_loader_version
        accessWidener file("src/main/resources/online-emotes.classtweaker")
    }

    defaultRemapJar = false
}

unimined.minecraft(sourceSets.fabric) {
    combineWith(sourceSets.main)

    fabric {
        loader fabric_loader_version
        accessWidener file("src/main/resources/online-emotes.classtweaker")
    }
    defaultRemapJar = true
}

unimined.minecraft(sourceSets.neoforge) {
    combineWith(sourceSets.main)

    neoForge {
        loader("net.neoforged:neoforge:$neoforge_version:universal")
        mixinConfig("online-emotes.mixins.json")

        // accessTransformer aw2at(file("src/main/resources/online-emotes.classtweaker"))
    }
    defaultRemapJar = true
}

dependencies {
    // Core
    implementation platformInclude("org.redlance.platformtools:common:$platformtools_version") { transitive = false }
    implementation platformInclude("org.redlance.platformtools:referer:$platformtools_version") { transitive = false }

    // Common
    compileOnly("io.github.kosmx.emotes:archCommon:$emotecraft_version")

    // Fabric
    fabricImplementation("io.github.kosmx.emotes:emotesFabric:$emotecraft_version")
    fabricImplementation("com.terraformersmc:modmenu:$modmenu_version") { transitive = false }

    // Neoforge
    neoforgeImplementation("io.github.kosmx.emotes:emotesNeo:$emotecraft_version")
}

shadowJar {
    configurations = [project.configurations.shadow]

    from(tasks.named("remapFabricJar").map { zipTree(it.archiveFile) })
    from(tasks.named("remapNeoforgeJar").map { zipTree(it.archiveFile) })

    archiveClassifier.set "fat"

    // Services
    filesMatching('META-INF/services/**') {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
    mergeServiceFiles()

    // Fix fabric jij
    filesMatching("META-INF/jarjar/*.jar") {
        path = path.replace("META-INF/jarjar/", "META-INF/jars/")
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
    filesMatching('META-INF/jarjar/metadata.json') {
        filter { it.replace('META-INF/jarjar/', 'META-INF/jars/') }
    }
}

[tasks.processResources, tasks.processFabricResources, tasks.processNeoforgeResources].each {
    def buildProps = rootProject.properties.clone()
    buildProps.put("version", version)

    // Another workaround
    buildProps.put("fabric_minecraft_version", minecraft_version.replace('-snapshot-', '-alpha.'))

    it.filesMatching(["META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
        expand buildProps
    }
}

var optimizeJar = tasks.register("optimizeJar", OptimizeJarsTask) {
    input.set(tasks.shadowJar.archiveFile)
    output.set(layout.buildDirectory.file("libs/${project["archives_base_name"]}-${version}.jar"))

    sourceFileStriping.enabled = true

    png.compressionLevel.set(9)
    png.compressorIterations.set(32)
    png.enabled = false
}

tasks.named("assemble") {
    finalizedBy(optimizeJar)
}

tasks.register("publishToDiscord", PublishDiscordTask) {
    username.set("Online Emotes Updates")
    url.set(providers.environmentVariable("DISCORD_WEBHOOK"))
    avatar.set("https://raw.githubusercontent.com/dima-dencep/online-emotes/HEAD/src/main/resources/assets/online-emotes/icon.png")

    container {
        it.title = "## ✨ Online Emotes\n### v${version} is out!"
        it.description = "### What's new:\n${providers.environmentVariable("MOD_CHANGELOG").orElse("").get()}"

        it.thumbnail("https://raw.githubusercontent.com/dima-dencep/online-emotes/HEAD/src/main/resources/assets/online-emotes/icon.png")
        it.timestamp(System.currentTimeMillis())
    }

    links {
        it.fromEnvHack()
    }

    footer = "||<@&1136394910103257229>||"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set 25
}

jar {
    archiveClassifier.set "dev"
}
