# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Properties
    minecraft_version = 26.1.2
    fabric_loader_version = 0.19.2
    neoforge_version = 26.1.2.81

# Mod Properties
    mod_version = 3.4.9
    maven_group = org.redlance.dima_dencep.mods
    archives_base_name = online-emotes

# Dependencies
    emotecraft_version = 3.3.0-b.build.160
    modmenu_version = 20.0.1
    platformtools_version = 4.2.2
