# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Properties
    minecraft_version = 1.21.4
    parchment_version = 2025.03.23
    loader_version = 0.16.14
    forge_version = 21.4.136

# Mod Properties
    mod_version = 3.3.3.1
    maven_group = org.redlance.dima_dencep.mods
    archives_base_name = online-emotes

# Dependencies
    emotecraft_version = 2.5.7
    fcapip_version = 21.4.1
    velocity_version = 3.4.0-SNAPSHOT
    netty_version = 4.1.115.Final
    fabric_version = 0.119.2+1.21.4
    platformtools_version = 0.0.1
