# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Properties
    minecraft_version = 1.21.9
    parchment_version = 2025.09.14
    loader_version = 0.17.2
    forge_version = 21.9.0-beta

# Mod Properties
    mod_version = 3.4.3
    maven_group = org.redlance.dima_dencep.mods
    archives_base_name = online-emotes

# Dependencies
    emotecraft_version = 3.1.0-b.build.124
    fcapip_version = 21.9.5
    velocity_version = 3.4.0-SNAPSHOT
    fabric_version = 0.133.14+1.21.9
    platformtools_version = 2.0.0
