architectury {
    common("neoforge", "fabric")
}

loom {
    accessWidenerPath = file("src/main/resources/online-emotes.accesswidener")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"

    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${fcapip_version}"
    modCompileOnly("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${fcapip_version}") {
        transitive = false
    }

    // EmoteCraft
    modImplementation "dev.kosmx.player-anim:player-animation-lib:${playeranimator_version}"
    modImplementation "dev.kosmx.player-anim:anim-core:${playeranimator_version}"
    modImplementation "maven.modrinth:emotecraft:${emotecraft_version}-fabric"

    implementation("io.netty:netty-codec-http:${netty_version}") {
        transitive = false
    }
}

jar {
    from rootProject.file("LICENSE")
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }
}
